---
title: "intro"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{intro}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
mypath <- rprojroot::find_package_root_file
```

```{r setup}
library(tidyverse)
library(magrittr)
library(knitr)
source(mypath("R/misc.R"))
```



```{r pond-data}
pond_species_list <- read_csv(mypath("data-raw/plando_fish_list.csv"))
pond_sampling <- read_csv(mypath("data-raw/plando_sampling_year.csv"))
pond_spatial_coord <- read_csv(mypath("data-raw/plando_spatial_ coordinates.csv"))
```
```{r metaweb-data}
myload(metaweb_analysis, diet_shift, species,
  dir = "~/Documents/post-these/mnhn/fishcom/data")
sp <- species %>% 
  filter(code %in% metaweb_analysis$species)
rm(species)
```

## Check species



```{r}
sp_in_pond <- sp %>% 
  filter(latin_name %in% pond_species_list$species)

sp_not_in_pond <- pond_species_list %>% 
  filter(!species %in% sp$latin_name)

# carassius
sp$latin_name[str_detect(sp$latin_name, "Car")]
# Liza / Chelon 
sp$latin_name[str_detect(sp$latin_name, "Chelon")]
sp$latin_name[str_detect(sp$latin_name, "Liza")]
# Salve 
sp$latin_name[str_detect(sp$latin_name, "Salve")]

sp$latin_name[str_detect(sp$latin_name, "Che")]
sp$latin_name[str_detect(sp$latin_name, "Cor")]
sp$latin_name[str_detect(sp$latin_name, "Gaste")] #OK
sp$latin_name[str_detect(sp$latin_name, "Gymno")] #OK
sp$latin_name[str_detect(sp$latin_name, "Leuc")]
sp$latin_name[str_detect(sp$latin_name, "Salmo")] #Ok
sp$latin_name[str_detect(sp$latin_name, "Scar")]

sp_name_issue <- c("Gasterosteus aculeatus aculeatus", "Gymnocephalus cernuus", "Salmo trutta fario")
names(sp_name_issue) <- c("Gasterosteus aculeatus", "Gymnocephalus cernua", "Salmo trutta")

sp_in_pond <- sp %>% 
  filter(latin_name %in% c(pond_species_list$species, sp_name_issue))
```

```{r}
# Check the species synonyms:
#Carassius auratus auratus <-> Carassius auratus

#Carassius auratus gibelio <-> Carassius gibelio
#Liza aurata <-> Chelon auratus
#Liza ramada <-> Chelon ramada
#Salvelinus umbla <-> Salvelinus alpinus
```

```{r}
sp_pond_in_diet <- sp %>%
  filter(code %in% unique(diet_shift[diet_shift$species %in% sp_in_pond$code, ]$species)) 

```

Over the `r length(unique(pond_species_list$species))` species present in the ponds, we have `r length(unique(sp_pond_in_diet$code))` species which are present in our dataset.

```{r}
pond_species_check <- pond_species_list %>%
  mutate(
    present_in_metaweb = ifelse(species %in% 
      c(sp_pond_in_diet$latin_name, names(sp_name_issue)),
    TRUE, FALSE)) %>%
  arrange(present_in_metaweb)

pond_species_check %>%
  knitr::kable()
```

## Spatial coordinates

```{r}
# get station from hard drive
#myload(op, station, dir = "~/Documents/post-these/mnhn/fishcom/data-raw")

library(sf)
myload(region_polygon, op_analysis, station_analysis, dir = "~/Documents/post-these/mnhn/fishcom/data")
# get the map

pond_spatial_coord %<>% 
  na.omit %>%
  st_as_sf(coords = c("long_plando", "lat_plando"), crs = 4326)
```

```{r, fig.dim = c(10,10)}
plot(st_geometry(region_polygon), lwd = 1.5, col = "grey95")
plot(st_geometry(station_analysis), pch = 20, col = "red", add = T)
plot(st_geometry(pond_spatial_coord), pch = 20, col = "green", add = T)

legend("bottomright", c("Stream", "Pond"), pch=20, col = c("red", "green"), title= "Communities sampled")
```


