---
title: Building local network and metrics
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  echo = FALSE
)
```

```{r setup}
library(tidyverse)
library(magrittr)
library(kableExtra)
library(igraph)
#library(sizeTrophicInteractions)
library(furrr)

mypath <- rprojroot::find_package_root_file
source(mypath("R", "misc.R"))
source(mypath("R", "local_network_build.R"))
source(mypath("R", "metaweb_build.R"))
source(mypath("R", "plot_code_webs.R"))
source_dir(mypath("R"))
```

```{r load}
myload(ind_size, metaweb_lake, metaweb_analysis, length_analysis,
  dir = mypath("data"))
```

```{r}
metaweb_stream <- metaweb_analysis
```


# Local network

```{r get network, cache = TRUE}
code_species_river_lake <- read.delim(paste0(mypath("outputs"), "/code_species_river_lake.txt"))
code_species_lake <- code_species_river_lake %>% select(sp_code, sp_lake) %>% drop_na(.)  
code_species_lake$sp_lake <- gsub(" ", "_", code_species_lake$sp_lake)
colnames(code_species_lake)[2] <- "species"
ind_size <- left_join(ind_size, code_species_lake, by = "species")
ind_size <- ind_size %>% select(id_campagne, sp_code, fish)
colnames(ind_size)[2] <- "species"

network_lake <- build_local_network(
  data = filter(ind_size, species %in% metaweb_lake$size_class$species),
  species = species,
  var = fish,
  group_var = id_campagne,
  metaweb = metaweb_lake,
  classes = NULL,
  out_format = "igraph"
)

# check
network_lake %>%
  unnest(data) %>%
  filter(is.na(class_id))

mysave(network_lake, dir = mypath("data"), overwrite = TRUE)

network_stream <- build_local_network(
  data = filter(length_analysis,
    species %in% metaweb_stream$size_class$species),
  species = species,
  var = length,
  group_var = opcod,
  metaweb = metaweb_stream,
  classes = NULL,
  out_format = "igraph"
)

# check
network_stream %>%
  unnest(data) %>%
  filter(is.na(class_id))
mysave(network_stream, dir = mypath("data"), overwrite = TRUE)
```

```{r, eval=TRUE, fig.dim = c(7, 7)}

sp_color <- set_color_species(
  node_list = colnames(metaweb_lake$metaweb),
  species_list = metaweb_lake$species,
  resource_list = metaweb_lake$resource
)

names(sp_color)[names(sp_color) %in% metaweb_lake$resource] <-
  c("detritivore", "biofilm", "phytobenthos", "macrophage", "phytoplankton", "zooplankton", "zoobenthos")
node_sp <- str_remove(colnames(metaweb_lake$metaweb), "_\\d+")

TL <- NetIndices::TrophInd(metaweb_lake$metaweb)$TL
net_ex <- network_lake$network[[1]] %>%
graph_from_data_frame() %>%
  as_adjacency_matrix(., sparse = FALSE)

node_sp <- str_remove(colnames(net_ex), "_\\d+")

TL <- NetIndices::TrophInd(net_ex)$TL

PlotWeb(
  TL = TL,
  webTL = net_ex,
  colnode = sp_color[node_sp],
  abund = 6,
  collink = "grey90",
  scale_abun = .01
)

legend(
  x      = "bottom",
  inset = 0,
  legend = names(sp_color)[names(sp_color) %in% node_sp],
  pch    = 21,
  col    = "#777777",
  pt.bg  = sp_color[names(sp_color) %in% node_sp],
  pt.cex = 0.7,
  cex    = .5,
  bty    = "n",
  x.intersp = 1,
  text.width = .1,
  ncol   = 6
)

```

## Get network connectance, Tmax and richness 

```{r}
plan(multicore, workers = 3)
```


```{r, cache = TRUE}
network_stream %<>%
  mutate(
    network = future_map(network, igraph::graph_from_data_frame, directed = TRUE),
    network = future_map(network, igraph::as_adjacency_matrix, sparse = FALSE)
    )
# Compute generic indices:
network_stream_metrics <- network_stream %>%
  mutate(
    metrics = future_map(network, NetIndices::GenInd),
    connectance = map_dbl(metrics, "C"),
    nbnode = map_dbl(metrics, "N")
  )
```

```{r}
network_stream_metrics %<>%
  mutate(
    troph = future_map(network, NetIndices::TrophInd)
    )

network_stream_metrics %<>%
  mutate(
    obs_troph_level = map(troph, function(x) {
      out <- tibble(
        species_name = row.names(x),
        obs_troph_level = x$TL
      )
      return(out)
    }),
  max_troph_lvl = map_dbl(troph, ~max(.x$TL))
  )

mysave(network_stream_metrics, dir = mypath("data"), overwrite = TRUE)
```


```{r, cache = TRUE}
network_lake %<>%
  mutate(
    network = future_map(network, igraph::graph_from_data_frame, directed = TRUE),
    network = future_map(network, igraph::as_adjacency_matrix, sparse = FALSE)
    )
# Compute generic indices:
network_lake_metrics <- network_lake %>%
  mutate(
    metrics = future_map(network, NetIndices::GenInd),
    connectance = map_dbl(metrics, "C"),
    nbnode = map_dbl(metrics, "N")
  )
network_lake_metrics %<>%
  select(-data, metrics)
```

```{r}
network_lake %<>%
  mutate(
    troph = future_map(network, NetIndices::TrophInd)
    )

network_lake %>%
  select(id_campagne, troph) %>%
  unnest(troph) %>%
  filter(is.na(TL))
network_lake$troph[[1]]
## get obs_troph_level
network_lake %<>%
  mutate(
    obs_troph_level = map(troph, function(x) {
      out <- tibble(
        species_name = row.names(x),
        obs_troph_level = x$TL
      )
      return(out)
    }),
  max_troph_lvl = map_dbl(troph, ~max(.x$TL))
  )
network_lake_metrics %<>%
  left_join(select(network_lake, id_campagne, obs_troph_level, max_troph_lvl), by =
    "id_campagne")

mysave(network_lake_metrics, dir = mypath("data"), overwrite = TRUE)
```

## Compute weighted average trophic level

```{r bm by size class}
myload(
  weight_fish_stream, weight_fish_lake,
  metaweb_stream, metaweb_lake,
  dir = mypath("data")
)

size_class_weight_stream <- assign_size_class(
  data = filter(weight_fish_stream, species %in% metaweb_stream$size_class$species),
  species = species, var = length,
  classes = metaweb_stream$size_class) %>%
  unite(sp_class, species, class_id, sep = "_") %>%
  dplyr::select(opcod, sp_class, weight) %>%
  group_by(opcod, sp_class) %>%
  summarise(bm = sum(weight)) %>%
  ungroup()


size_class_weight_lake <- assign_size_class(
  data = weight_fish_lake %>%
    filter(!is.na(fish),
      species %in% metaweb_lake$size_class$species),
  species = species, var = fish,
  classes = metaweb_lake$size_class
    ) %>%
  unite(sp_class, species, class_id, sep = "_") %>%
  dplyr::select(id_campagne, sp_class, weight) %>%
  group_by(id_campagne, sp_class) %>%
  summarise(bm = sum(weight)) %>%
  ungroup()

```

```{r stream weighted tlvl}
myload(network_stream_metrics, dir = mypath("data"))

obs_troph_level <- network_stream_metrics %>%
  select(opcod, obs_troph_level) %>%
  unnest() %>%
  rename(sp_class = species_name) %>%
  left_join(size_class_weight_stream, by = c("opcod", "sp_class"))

weighted_trophic_lvl <- obs_troph_level %>%
  filter(!sp_class %in% metaweb_stream$resource) %>%
  group_by(opcod) %>%
  summarise(
    w_trph_lvl_avg = round(sum(obs_troph_level * bm / sum(bm)), 2)
  )

if ("w_trph_lvl_avg" %in% colnames(network_stream_metrics)) {
  network_stream_metrics %<>% select(-w_trph_lvl_avg)
}

network_stream_metrics %<>%
  left_join(weighted_trophic_lvl, by = "opcod")

mysave(network_stream_metrics, dir = mypath("data"), overwrite = TRUE)
```

```{r lake weighted tlvl}
myload(network_lake_metrics, dir = mypath("data"))

obs_troph_level <- network_lake_metrics %>%
  select(id_campagne, obs_troph_level) %>%
  unnest() %>%
  rename(sp_class = species_name) %>%
  left_join(size_class_weight_lake, by = c("id_campagne", "sp_class"))

weighted_trophic_lvl <- obs_troph_level %>%
  filter(!sp_class %in% metaweb_lake$resource) %>%
  group_by(id_campagne) %>%
  summarise(
    w_trph_lvl_avg = round(sum(obs_troph_level * bm / sum(bm)), 2)
  )

if ("w_trph_lvl_avg" %in% colnames(network_lake_metrics)) {
  network_lake_metrics %<>% select(-w_trph_lvl_avg)
}

network_lake_metrics %<>%
  left_join(weighted_trophic_lvl, by = "id_campagne")

mysave(network_lake_metrics, dir = mypath("data"), overwrite = TRUE)
```


