---
title: "metaweb"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{metaweb}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  echo = FALSE
)
```

```{r setup}
library(tidyverse)
library(magrittr)
library(kableExtra)
library(igraph)
install.packages("~/Documents/post-these/packages/sizeTrophicInteractions_0.0.0.9000.tar.gz")
library(sizeTrophicInteractions)

mypath <- rprojroot::find_package_root_file
source(mypath("R", "misc.R"))
source_dir(mypath("R"))
```


```{r load}
myload(diet_shift, ind_size, dir = mypath("data"))
```

# Get species names

```{r}
sp_in_pond <- unique(ind_size$species)
```


### Fix name differences

```{r}
species %<>%
  mutate(
    latin_name = str_replace_all(latin_name, " ", "_"),
  )
species$latin_name_fixed <- species$latin_name
species[species$latin_name_fixed == "Gasterosteus_aculeatus_aculeatus", ]$latin_name_fixed <- 
  "Gasterosteus_aculeatus"
species[species$latin_name_fixed == "Gymnocephalus_cernuus", ]$latin_name_fixed <- 
  "Gymnocephalus_cernua"
#species[species$latin_name_fixed == "Salmo_trutta_fario", ]$latin_name_fixed <- 
  #"Salmo_trutta"
```


```{r, eval = FALSE}
species %>%
  filter(latin_name_fixed %in% sp_in_pond)
sp_in_pond[which(!sp_in_pond %in% species$latin_name_fixed)]
```


### Species in ponds that are not in diet shift

```{r missing-ind}
pond_species_not_in_diet <-
  sp_in_pond[which(!sp_in_pond %in% diet_shift$species_name)]

nb_ind_not_in_diet <-
  length(which(ind_size$species %in% pond_species_not_in_diet))

missing_ind_size <-
  ind_size %>%
  filter(species %in% pond_species_not_in_diet) %>%
  group_by(species) %>%
  summarise(n = n()) %>%
  arrange(desc(n)) 

missing_ind_size %>%
  kable(.,
    caption = "Number of individuals by species missing in food diet data",
    label = "missing-ind"
  )
```

There are `r length(pond_species_not_in_diet)` that are not in diet data,
`r nb_ind_not_in_diet` individuals, i.e. a proportion of 
`r nb_ind_not_in_diet/nrow(ind_size) %>% round(., 2)`. However, half of the
missing individuals are represented by "Sander_lucioperca".

# Build the metaweb

```{r prep data}
myload(species, pred_win, diet_shift, resource_diet_shift,
  dir = mypath("data"))

species_code_name <-
  diet_shift %>%
  distinct(species, species_name)
pred_win %<>%
  left_join(species_code_name, by = "species")
ind_size %<>%
 rename(species_name = "species")
diet_shift %<>%
  select(-species) %>%
  mutate(
    size_max = str_replace(size_max, "max", "Inf"),
    size_max = as.numeric(size_max)
  )
resource_diet_shift %<>%
 rename(species_name = "species_code") %>%
  select(-species)
pred_win %<>%
  select(-species)
```


```{r build metaweb, cache=TRUE}
metaweb_lake <- build_metaweb(
  data = ind_size,
  species = species_name,
  size = fish,
  pred_win = pred_win,
  beta_min = beta_min,
  beta_max = beta_max,
  fish_diet_shift = (diet_shift),
  low_bound = size_min,
  upper_bound = size_max,
  fish = fish,
  resource_diet_shift = resource_diet_shift,
  class_method = "percentile",
  nb_class = 9,
  pred_win_method = "midpoint",
  fish_resource_method = "midpoint",
  na.rm = TRUE,
  replace_min_by_one = FALSE)

mysave(metaweb_lake, dir = mypath("data"), overwrite = TRUE)
```


```{r, fig.dim=c(7,7)}
# species_list
sp_color <- set_color_species(
  node_list = colnames(metaweb_lake$metaweb),
  species_list = metaweb_lake$species,
  resource_list = metaweb_lake$resource
)

names(sp_color)[names(sp_color) %in% metaweb_lake$resource] <-
  c("detritivore", "biofilm", "phytobenthos", "macrophage", "phytoplankton", "zooplankton", "zoobenthos")
node_sp <- str_remove(colnames(metaweb_lake$metaweb), "_\\d+")

TL <- NetIndices::TrophInd(metaweb_lake$metaweb)$TL

#dev.new(width = 5, height = 7, units = "in")
## i3: mod + shift + space 
#
#png(
#  filename = mypath("manuscript/bef_stability/figs",
#    "metaweb2.png"), 
#  units = "in",
#  width = 5,
#  height = 7,
#  pointsize = 12*96/72,
#  res = 200 
#)
org_par <- par(
  mar = c(4, 0, 1, 0) + 0,
  oma = c(0, 0, 0, 0),
  xpd = NA
)
PlotWeb(
  TL = TL,
  webTL = metaweb_lake$metaweb,
  colnode = sp_color[node_sp],
  abund = 6,
  collink = "grey90",
  scale_abun = .01
)
title("Lake Metaweb")

legend(
#  x      = 0.031,
#  y      = 4,
  x      = "bottom",
  inset = -.07,
  legend = names(sp_color),
  pch    = 21,
  col    = "#777777",
  pt.bg  = sp_color,
  pt.cex = 0.7,
  cex    = .8,
  bty    = "n",
  x.intersp = 1.5,
  text.width = .1,
  ncol   = 6

)

#dev.off()
par(org_par)
```

```{r load both metaweb}
myload(metaweb_analysis, metaweb_lake, dir = mypath("data"))
metaweb_stream <- metaweb_analysis
mysave(metaweb_stream, dir = mypath("data"), overwrite = TRUE)
```
```{r, fig.dim=c(7,7)}
# species_list
sp_color <- set_color_species(
  node_list = colnames(metaweb_stream$metaweb),
  species_list = metaweb_stream$species,
  resource_list = metaweb_stream$resource
)

names(sp_color)[names(sp_color) %in% metaweb_stream$resource] <-
  c("detritivore", "biofilm", "phytobenthos", "macrophage", "phytoplankton", "zooplankton", "zoobenthos")
node_sp <- str_remove(colnames(metaweb_stream$metaweb), "_\\d+")

TL <- NetIndices::TrophInd(metaweb_stream$metaweb)$TL

PlotWeb(
  TL = TL,
  webTL = metaweb_stream$metaweb,
  colnode = sp_color[node_sp],
  abund = 6,
  collink = "grey90",
  scale_abun = .01
)
title("Stream Metaweb")

legend(
#  x      = 0.031,
#  y      = 4,
  x      = "bottom",
  inset = -.07,
  legend = names(sp_color),
  pch    = 21,
  col    = "#777777",
  pt.bg  = sp_color,
  pt.cex = 0.7,
  cex    = 1,
  bty    = "n",
  x.intersp = 1.5,
  text.width = .1,
  ncol   = 6

)

#dev.off()
par(org_par)
```



## Metaweb comparison

```{r compute index, cache=TRUE}
ind_lake <- metaweb_lake$metaweb %>%
  NetIndices::GenInd() %>%
  c(., Tlvl = mean(NetIndices::TrophInd(metaweb_lake$metaweb)$TL))
ind_stream <- metaweb_stream$metaweb %>%
  NetIndices::GenInd() %>%
  c(., Tlvl = mean(NetIndices::TrophInd(metaweb_stream$metaweb)$TL))
```

```{r}
ind_net_to_keep <- c("N", "Ltot", "LD", "C", "Tlvl")

metaweb_metric <- map2_dfr(
  list(ind_lake, ind_stream),
  list("lake", "stream"),
  function(l, type, cols_to_keep) {
    l %>%
      enframe() %>%
      unnest(value) %>%
      filter(name %in% cols_to_keep) %>%
      mutate(type = type)
  }, cols_to_keep = ind_net_to_keep
)

metaweb_metric %>%
  pivot_wider(names_from = name, values_from = value) %>%
  kable(.,
    label = "tab:metaweb-comp",
    caption = "Comparision of the two metawebs."
  )
```

```{r prop-pisc}
get_prop_pisc <- function(metaweb = NULL) {

  mask_fish_metaweb <-
    str_remove(colnames(metaweb$metaweb), "_\\d+") %in%
    metaweb$species

  fish_fish_metaweb <- metaweb$metaweb[mask_fish_metaweb, mask_fish_metaweb]
  # Nb of piscivores:
  tibble(
    nb_pisc = length(which(colSums(fish_fish_metaweb) > 0)),
    prop_pisc = length(which(colSums(fish_fish_metaweb) > 0)) /
      length(colSums(fish_fish_metaweb))
  )
}
prop_pisc <- map_dfr(list(metaweb_lake, metaweb_stream), get_prop_pisc) %>%
  mutate(type = c("Lake", "Stream"))
prop_pisc %>%
  kable(.,
    label = "tab:pisc",
    caption = "Proportion of piscivores nodes in metawebs"
  )
```


