---
title: "Supporting Information"
author: ""
date: ""
output:
  pdf_document:
    fig_caption: yes
header-includes:
  - \usepackage{caption}
  - \DeclareCaptionLabelFormat{nospace}{#1#2}
  - \captionsetup[figure]{labelformat=nospace}
  - \captionsetup[table]{labelformat=nospace}
  - \usepackage[labelfont={bf}]{caption}
label:
    fig: "**Figure S**"
    tab: "**Table S**"

---

```{r setup, include = FALSE}
library(dplyr)
library(GGally)
library(ggplot2)
library(ggspatial)
library(rgdal)
library(rnaturalearth)
library(sf)


mypath <- rprojroot::find_package_root_file
source(mypath("R", "misc.R"))

myload(dataset_lake_stream, dir = mypath("data")) 
dataset_lake_stream$type[dataset_lake_stream$type == 'stream'] <- 'Stream'
dataset_lake_stream$type[dataset_lake_stream$type == 'lake'] <- 'Lake'
```


\def\figurename{Figure S}
\def\tablename{Table S}


```{r scriptMapSamplingSites, include = FALSE , echo = FALSE, message = FALSE, warning = FALSE}

worldmap <- ne_countries(continent = 'europe', scale = 'large', type = 'countries', returnclass = 'sf')
fr <- data.frame(Country = "France", Focus = "YES") 
world_joined <- left_join(worldmap, fr, by = c("name" = "Country"))
francemap <- ne_countries(country = 'france', scale = 'large', type = 'countries', returnclass = 'sf')
lakes <- readOGR(mypath("data-raw/ne_10m_lakes"), layer="ne_10m_lakes") 
lakes <- st_as_sf(lakes)
rivers <- readOGR(mypath("data-raw/ne_10m_rivers_lake_centerlines"), layer="ne_10m_rivers_lake_centerlines") 
rivers <- st_as_sf(rivers)
sf::sf_use_s2(FALSE)
francelakes <- st_intersection(st_as_sf(lakes), st_as_sf(francemap))
francerivers <- st_intersection(st_as_sf(rivers), st_as_sf(francemap))
BassinHydrographique <- readOGR(mypath("data-raw/BassinsHydrographiques_Métropole2019_BDTopage"), layer="BassinHydrographique") 
BassinHydrographique <- st_as_sf(BassinHydrographique)
BassinHydrographique <- st_transform(BassinHydrographique, crs = st_crs(francemap))
BassinHydrographique <- st_intersection(st_as_sf(BassinHydrographique), st_as_sf(francemap))

```

```{r figMapSamplingSites, echo = FALSE, message = FALSE, warning = FALSE, fig.width = 7, fig.height = 7, fig.cap="Metropolitan France map showing the geographical distribution of the 629 sites, where taxonomic and environmental data have been collected. Green points represent sampled lakes (n = 256), purple points represent sampled streams (n = 373) and grey borders into France represent the 7 hydrographic basins."}

ggplot() +
  geom_sf(data = world_joined, fill = "white", color = "black", size = 0.05) +
  geom_sf(data = BassinHydrographique, fill = "#f0f0f0", color = "#bdbdbd", size = 0.25) +
  geom_sf(data = francelakes, col = '#6baed6', fill = '#6baed6', size = 0.05) +
  geom_sf(data = francemap, fill = alpha("white", 0), color = "black", size = 0.6) +
  annotation_scale(location = "bl", width_hint = 0.1) +
  annotation_north_arrow(which_north = "true", location = "tr", height = unit(0.5, "cm"), width = unit(0.5, "cm"), style = north_arrow_orienteering(fill = c("black", "black"), text_size = 6)) +
  geom_point(data = dataset_lake_stream,
             aes(x = long, y = lat, fill = type), shape = 21, colour = "#000000", size = 2) +
  scale_fill_manual(values = c("#8da0cb", "#66c2a5"), name = "Communities samples") +
  coord_sf(xlim = c(-5, 9.75), ylim = c(41.3, 51.5), expand = FALSE) +
  theme(title = element_text(),
        plot.title = element_text(margin = margin(20,20,20,20), size = 18, hjust = 0.5),
        axis.text.x = element_blank(), axis.text.y = element_blank(),
        axis.ticks = element_blank(),
        axis.title.x = element_blank(),  axis.title.y = element_blank(),
        panel.grid.major = element_blank(), panel.background = element_blank(),
        strip.background = element_rect(fill = "#000000", color = "#000000", size = 1, linetype = "solid"),
        strip.text.x = element_text(size = 12, color = "#ffffff", face = "bold"),
        panel.border = element_rect(colour = "#000000", fill = NA, size = 1)) +
  theme(legend.position = c(0.15, 0.10), legend.background = element_blank(), legend.key = element_blank())

```



```{r figBODNutrients, echo = FALSE, message = FALSE, warning = FALSE, fig.width = 7, fig.height = 7, fig.cap="Scatterplot matrix of BOD and nutrients for the sampled lakes (in purple) and streams (in green). Scatterplots of each pair of numeric variable are drawn on the left part of the figure. Pearson correlation is displayed on the right. Variable distribution is available on the diagonal. The variable *TN* refers to total nitrogen and *TP* corresponds to total phosphorus"}

ggpairs(dataset_lake_stream, columns = c(5, 20:21), ggplot2::aes(colour = type),
        lower = list(continuous = wrap("smooth", alpha = 0.2)),
        columnLabels = c("BOD (mg/L)", "TN (mg/L)", "TP (mg/L)")) +
  scale_colour_manual(values = c("#8da0cb", "#66c2a5")) +
  scale_fill_manual(values = c("#8da0cb", "#66c2a5")) +
  theme_bw() +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        legend.position = "bottom",
        axis.text = element_text(size = 14, colour = "#000000"),
        strip.text.x = element_text(size = 16, face = "bold"),
        strip.text.y = element_text(size = 16, face = "bold"))

```



```{r figFWEnvproperties, echo = FALSE, message = FALSE, warning = FALSE, fig.width = 10, fig.height = 10, fig.cap="Scatterplot matrix of food-web and environmental properties for the sampled lakes (in purple) and streams (in green). Scatterplots of each pair of numeric variable are drawn on the left part of the figure. Pearson correlation is displayed on the right. Variable distribution is available on the diagonal. The variable *Rich.* refers to the trophic species richness, *Connect.* corresponds to the connectance, *Max. troph. level* corresponds to the maximum trophic level, and *Temp.* refer to the temperature."}

ggpairs(dataset_lake_stream, columns = c(8, 9, 7 , 11, 6, 5), ggplot2::aes(colour = type),
        lower = list(continuous = wrap("smooth", alpha = 0.2)),
        columnLabels = c("Rich.", "Nodes", "Connect.", "Max. troph. level", "Temp. (°C)", "DBO (mg/L)")) +
  scale_colour_manual(values = c("#8da0cb", "#66c2a5")) +
  scale_fill_manual(values = c("#8da0cb", "#66c2a5")) +
  theme_bw() +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        legend.position = "bottom",
        axis.text = element_text(size = 10, colour = "#000000"),
        strip.text.x = element_text(size = 12, face = "bold"),
        strip.text.y = element_text(size = 12, face = "bold"))

```
